//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEXtrading
    {
        public string CompanyName { get; set; }
        public string Symbol { get; set; }
        public string ChangePercent { get; set; }
        public string AvgTotalVolume { get; set; }
        public string LatestPrice { get; set; }
        public string Open { get; set; }
        public string High { get; set; }
        public string Low { get; set; }
        public string Week52High { get; set; }
        public string Year52Low { get; set; }
        public System.DateTime Date { get; set; }
        public int ScrapeId { get; set; }
    }
}
