//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScraper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockInfoEntities1 : DbContext
    {
        public StockInfoEntities1()
            : base("name=StockInfoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurrentStockInfo> CurrentStockInfoes { get; set; }
        public virtual DbSet<HistoryOfStockInfo> HistoryOfStockInfoes { get; set; }
        public virtual DbSet<IEXtrading> IEXtradings { get; set; }
        public virtual DbSet<WorldTradingData> WorldTradingDatas { get; set; }
        public virtual DbSet<WorldTradingDataHistory> WorldTradingDataHistories { get; set; }
        public virtual DbSet<CNNmoneyStock> CNNmoneyStocks { get; set; }
    }
}
